lesson2/Assignment2/Assignment2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('asigm_1_app', include('asigm_1_app.urls')),
    path('asigm_1_proj', include('asigm_1_proj.urls'))
]

lesson2/Assignment2/asigm_1_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
]

lesson2/Assignment2/asigm_1_proj/urls.py
from . import views
from django.urls import path

app_name = 'asigm_1_proj'
urlpatterns = [
    path('', views.index, name='index'),
    path('/<int:person_id>', views.detail, name='detail' ),
    path('/add_user', views.addUser, name='adduser')
]

lesson2/Assignment2/asigm_1_app/models.py
from django.db import models

# Create your models here.

lesson2/Assignment2/asigm_1_proj/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    address = models.TextField()
    mobile_number = models.CharField(max_length=10, unique=True)

lesson2/Assignment2/asigm_1_proj/forms.py
from django import forms

class AddUser(forms.Form):
    name = forms.CharField(label='Name',max_length=50)
    age = forms.IntegerField(label='Age')
    address = forms.CharField(label='Address')
    mobile_number = forms.CharField(label='Mobile number',max_length=10)

lesson2/Assignment2/asigm_1_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    response = HttpResponse()
    response.write("<h1>This is my first Django application</h1>")
    return response

lesson2/Assignment2/asigm_1_proj/views.py
from unicodedata import name
from django.shortcuts import render
from .models import Person
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from .forms import AddUser
from django.contrib import messages
# Create your views here.

def index(request):
    person_list = Person.objects.all()
    template = loader.get_template('index.html')
    context = {
        'person_list': person_list
    }
    return HttpResponse(template.render(context, request))

def detail(request, person_id):
    try:
        person = Person.objects.get(pk=person_id)
    except Person.DoesNotExist:
        raise Http404("Person doesn't not exist")
    return render(request, 'detail.html', {'person':person})

def addUser(request):
    newUser = AddUser()
    if request.method == 'POST':
        newUser = Person(name = request.POST['name'], age=request.POST['age'],address=request.POST['address'],mobile_number=request.POST['mobile_number'] )
        if newUser.name != '':
            newUser.save()
            messages.info(request, 'Add user successfully!')
            return HttpResponseRedirect('/asigm_1_proj')
    
    return render(request, 'add.html', {'form': newUser})

lesson2/Assignment2/asigm_1_proj/templates/add.html
<form action="{%url 'asigm_1_proj:adduser' %}" method="post">
    {%csrf_token%}
    <table>
        {{form.as_table}}
    </table>
    
    <input type="submit" value="Add" />
</form>

lesson2/Assignment2/asigm_1_proj/templates/detail.html
<h2>Name: {{person.name}}</h2>
<h2>Age: {{person.age}}</h2>
<h2>Address: {{person.address}}</h2>
<h2>Mobile number: {{person.mobile_number}}</h2>

lesson2/Assignment2/asigm_1_proj/templates/index.html
{% if person_list %}
    <ul>
        {% for p in person_list %}
            <li>
                <a href="{% url 'asigm_1_proj:detail' p.id%}"> 
                    {{p.name}}
                </a>
            </li>
        {%endfor%}
    </ul>
{%else%}
    <p>No person are available.</p>
{%endif%}
<a href="{%url 'asigm_1_proj:adduser' %}">Add new User</a>