django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('user_auth/',include('user_auth.urls'))
]

django/mysite/polls/urls.py
from django.urls import path
from . import views
app_name = "polls"

# urlpatterns = [
#     path('', views.index, name='index')
# ]

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

django/mysite/user_auth/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('register/', include('views.register')),
]

django/mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)

class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()
    num_stars = models.IntegerField()

class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
# class MyPerson(Person):
# 	age = xxx
#     class Meta:
#         proxy = True
 
#     def do_something(self):
#         pass
    person_id = models.AutoField(primary_key=True)
    person_name = models.CharField(max_length=100)
    person_age = models.PositiveIntegerField()

class Manufacturer(models.Models):
	manufacturer = models.CharField(max_length=50)
class Car(models.Model):
    manufacturer = models.ForeignKey(Manufacturer,on_delete=models.CASCADE)
    car_brand = models.CharField(max_length=50)

django/mysite/polls/views.py
from urllib import response
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.shortcuts import get_object_or_404
from django.urls import reverse

# Create your views here.

# def index(request):
#     response = HttpResponse()
#     response.write("<h1>Welcome</h1>")
#     response.write("This is the polls app")
#     return response

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # output = ', '.join([q.question_text for q in latest_question_list])
    # return HttpResponse(output)
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request,question_id):
    # return HttpResponse("You're looking at question %s." % question_id)
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request,'polls/detail.html',{'question':question})

def results(request, question_id):
    # response = "You're looking at the results of question %s."
    # return HttpResponse(response % question_id)
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    # return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set_get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html'), {
            'question': question,
            'error_message': "You didn't select a choice.",
        }
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))

django/mysite/user_auth/views.py
from urllib import response
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse 
from .forms import RegisterForm

def register(request):

    if request.method == 'POST':
        response = HttpResponse()
        response.write("<h1> Thanks for registering</h1></br>")
        response.write("Your email: " + request.POST['email'] + "</br>")
        return response

    registerForm = RegisterForm()
    return render(request, 'user_auth/register.html', {'form':registerForm})

django/mysite/polls/templates/polls/detail.html
<h1>{{question.question_text }}</h1>
<!-- <ul>
    {% for choice in question.choice_set.all %} 
        <li>{{choice.choice_text }}</li>
    {% endfor %}
</ul> -->
{% if error_message %}

<strong>{{ error_message }}</strong>

{% endif %} 

<form action="{%url 'polls:vote' question.id%}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %} 
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    {% endfor %} 
    <input type="submit" value="Vote" />
</form>

django/mysite/polls/templates/polls/index.html
{% load static %} 
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %} 
    <ul>
        {% for question in latest_question_list %} 
        <li>
            <!-- /polls/{{question.id}}/ -->
            <a href ="{% url 'detail' question.id %}"> 
                {{ question.question_text }}
            </a>
        </li>
        {% endfor %} 
    </ul>
{% else %} 
    <p>No polls are available.</p>
{% endif %} 

django/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %} 
    <li>
    {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes | pluralize }}
    </li>
    {% endfor %} 
</ul>

<a href="{% url 'polls:detail' question.id %">Vote again?</a>

django/mysite/user_auth/templates/user_auth/register.html
<form action="" method="post">
    {% csrt_token %} 
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>